/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  identity: {
    Login: () => import('#app/identity/controllers/login_controller'),
    Logout: () => import('#app/identity/controllers/logout_controller'),
  },
}
