/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  agendas: {
    CreateAgenda: () => import('#app/agendas/controllers/create_agenda_controller'),
    DeleteAgenda: () => import('#app/agendas/controllers/delete_agenda_controller'),
    ListAgendas: () => import('#app/agendas/controllers/list_agendas_controller'),
    UpdateAgenda: () => import('#app/agendas/controllers/update_agenda_controller'),
  },
  appointmentWorkflow: {
    CreateAppointmentStatus: () => import('#app/appointment_workflow/controllers/create_appointment_status_controller'),
    DeleteAppointmentStatus: () => import('#app/appointment_workflow/controllers/delete_appointment_status_controller'),
    ListAppointmentStatuses: () => import('#app/appointment_workflow/controllers/list_appointment_statuses_controller'),
    MoveAppointmentStatus: () => import('#app/appointment_workflow/controllers/move_appointment_status_controller'),
    UpdateAppointmentStatus: () => import('#app/appointment_workflow/controllers/update_appointment_status_controller'),
  },
  booking: {
    BookAppointment: () => import('#app/booking/controllers/book_appointment_controller'),
    BookingLink: () => import('#app/booking/controllers/booking_link_controller'),
    ChangeAppointmentStatus: () => import('#app/booking/controllers/change_appointment_status_controller'),
    ConfirmAppointment: () => import('#app/booking/controllers/confirm_appointment_controller'),
    CreateAppointment: () => import('#app/booking/controllers/create_appointment_controller'),
    ShowCalendar: () => import('#app/booking/controllers/show_calendar_controller'),
    UpdateAppointment: () => import('#app/booking/controllers/update_appointment_controller'),
  },
  clients: {
    CreateClient: () => import('#app/clients/controllers/create_client_controller'),
    DeleteClient: () => import('#app/clients/controllers/delete_client_controller'),
    GetClient: () => import('#app/clients/controllers/get_client_controller'),
    ListClients: () => import('#app/clients/controllers/list_clients_controller'),
    UpdateClient: () => import('#app/clients/controllers/update_client_controller'),
  },
  identity: {
    Login: () => import('#app/identity/controllers/login_controller'),
    Logout: () => import('#app/identity/controllers/logout_controller'),
    Signup: () => import('#app/identity/controllers/signup_controller'),
  },
  medicalRecords: {
    CreateConsultation: () => import('#app/medical_records/controllers/create_consultation_controller'),
    CreatePrescription: () => import('#app/medical_records/controllers/create_prescription_controller'),
    CreateVaccine: () => import('#app/medical_records/controllers/create_vaccine_controller'),
    ListConsultations: () => import('#app/medical_records/controllers/list_consultations_controller'),
    UpdateConsultation: () => import('#app/medical_records/controllers/update_consultation_controller'),
    UpdatePrescription: () => import('#app/medical_records/controllers/update_prescription_controller'),
    UpdateVaccine: () => import('#app/medical_records/controllers/update_vaccine_controller'),
  },
  onboarding: {
    ShowOnboarding: () => import('#app/onboarding/controllers/show_onboarding_controller'),
    UpdateOnboarding: () => import('#app/onboarding/controllers/update_onboarding_controller'),
  },
  pets: {
    CreatePet: () => import('#app/pets/controllers/create_pet_controller'),
    DeletePet: () => import('#app/pets/controllers/delete_pet_controller'),
    GetPet: () => import('#app/pets/controllers/get_pet_controller'),
    ListPets: () => import('#app/pets/controllers/list_pets_controller'),
    UpdatePet: () => import('#app/pets/controllers/update_pet_controller'),
  },
  scheduling: {
    CreateClosedDate: () => import('#app/scheduling/controllers/create_closed_date_controller'),
    CreateScheduleDay: () => import('#app/scheduling/controllers/create_schedule_day_controller'),
    CreateTimeOff: () => import('#app/scheduling/controllers/create_time_off_controller'),
    DeleteClosedDate: () => import('#app/scheduling/controllers/delete_closed_date_controller'),
    DeleteScheduleDay: () => import('#app/scheduling/controllers/delete_schedule_day_controller'),
    DeleteTimeOff: () => import('#app/scheduling/controllers/delete_time_off_controller'),
    GetBookableDays: () => import('#app/scheduling/controllers/get_bookable_days_controller'),
    GetBookableSlots: () => import('#app/scheduling/controllers/get_bookable_slots_controller'),
    ListShifts: () => import('#app/scheduling/controllers/list_shifts_controller'),
    UpdateClosedDate: () => import('#app/scheduling/controllers/update_closed_date_controller'),
    UpdateScheduleDay: () => import('#app/scheduling/controllers/update_schedule_day_controller'),
    UpdateTimeOff: () => import('#app/scheduling/controllers/update_time_off_controller'),
    UpdateWorkingHours: () => import('#app/scheduling/controllers/update_working_hours_controller'),
  },
  search: {
    Search: () => import('#app/search/controllers/search_controller'),
  },
  services: {
    CreateService: () => import('#app/services/controllers/create_service_controller'),
    DeleteService: () => import('#app/services/controllers/delete_service_controller'),
    ListServices: () => import('#app/services/controllers/list_services_controller'),
    UpdateService: () => import('#app/services/controllers/update_service_controller'),
  },
  shared: {
    Dashboard: () => import('#app/shared/controllers/dashboard_controller'),
  },
  tenants: {
    UpdateTenant: () => import('#app/tenants/controllers/update_tenant_controller'),
  },
}
