/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

import BookingAppointmentCreated from '#app/booking/events/appointment_created'
import BookingAppointmentRescheduled from '#app/booking/events/appointment_rescheduled'

export const events = {
  booking: {
    AppointmentCreated: BookingAppointmentCreated,
    AppointmentRescheduled: BookingAppointmentRescheduled,
  },
}
