/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

import BookingAppointmentCreated from '#app/booking/events/appointment_created'

export const events = {
  booking: {
    AppointmentCreated: BookingAppointmentCreated,
  },
}
