/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const listeners = {
  booking: {
    BroadcastAppointmentCreated: () => import('#app/booking/listeners/broadcast_appointment_created'),
  },
}
