/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const listeners = {
  booking: {
    TransmitAppointmentListener: () => import('#app/booking/listeners/transmit_appointment_listener'),
  },
  notifications: {
    SendConfirmationListener: () => import('#app/notifications/listeners/send_confirmation_listener'),
    SendRescheduledListener: () => import('#app/notifications/listeners/send_rescheduled_listener'),
  },
}
