/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import type { UUID } from '#shared/types'
import { DateTime } from 'luxon'

export class AgendaAppointmentTypeSchema extends BaseModel {
  static $columns = ['agendaId', 'appointmentTypeId', 'createdAt', 'updatedAt'] as const
  $columns = AgendaAppointmentTypeSchema.$columns
  @column()
  declare agendaId: UUID
  @column()
  declare appointmentTypeId: UUID
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class AgendaSchema extends BaseModel {
  static $columns = ['color', 'createdAt', 'id', 'name', 'tenantId', 'updatedAt'] as const
  $columns = AgendaSchema.$columns
  @column()
  declare color: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: UUID
  @column()
  declare name: string
  @column()
  declare tenantId: UUID
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class AppointmentStatusSchema extends BaseModel {
  static $columns = ['color', 'createdAt', 'id', 'isCustom', 'name', 'sortOrder', 'tenantId', 'updatedAt'] as const
  $columns = AppointmentStatusSchema.$columns
  @column()
  declare color: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare id: string
  @column()
  declare isCustom: boolean
  @column()
  declare name: string
  @column()
  declare sortOrder: number
  @column()
  declare tenantId: UUID | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class AppointmentTypeSchema extends BaseModel {
  static $columns = ['color', 'createdAt', 'description', 'duration', 'id', 'name', 'price', 'tenantId', 'updatedAt'] as const
  $columns = AppointmentTypeSchema.$columns
  @column()
  declare color: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare description: string | null
  @column()
  declare duration: number
  @column({ isPrimary: true })
  declare id: UUID
  @column()
  declare name: string
  @column()
  declare price: number | null
  @column()
  declare tenantId: UUID
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class AppointmentSchema extends BaseModel {
  static $columns = ['agendaId', 'appointmentTypeId', 'bookingRef', 'clientId', 'createdAt', 'duration', 'endDate', 'id', 'petId', 'reminderSentAt', 'startDate', 'statusId', 'tenantId', 'updatedAt'] as const
  $columns = AppointmentSchema.$columns
  @column()
  declare agendaId: UUID
  @column()
  declare appointmentTypeId: UUID
  @column()
  declare bookingRef: string
  @column()
  declare clientId: UUID
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare duration: number
  @column.dateTime()
  declare endDate: DateTime
  @column({ isPrimary: true })
  declare id: UUID
  @column()
  declare petId: UUID
  @column.dateTime()
  declare reminderSentAt: DateTime | null
  @column.dateTime()
  declare startDate: DateTime
  @column()
  declare statusId: string
  @column()
  declare tenantId: UUID
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class BreedSchema extends BaseModel {
  static $columns = ['id', 'name', 'speciesId'] as const
  $columns = BreedSchema.$columns
  @column({ isPrimary: true })
  declare id: UUID
  @column()
  declare name: string
  @column()
  declare speciesId: UUID | null
}

export class ClientSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'firstName', 'id', 'lastName', 'notes', 'phone', 'tenantId', 'updatedAt'] as const
  $columns = ClientSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string | null
  @column()
  declare firstName: string
  @column({ isPrimary: true })
  declare id: UUID
  @column()
  declare lastName: string
  @column()
  declare notes: string | null
  @column()
  declare phone: string
  @column()
  declare tenantId: UUID
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ClosedDateSchema extends BaseModel {
  static $columns = ['createdAt', 'description', 'end', 'id', 'start', 'tenantId', 'updatedAt'] as const
  $columns = ClosedDateSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column.date()
  declare end: DateTime
  @column({ isPrimary: true })
  declare id: UUID
  @column.date()
  declare start: DateTime
  @column()
  declare tenantId: UUID
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class PetSchema extends BaseModel {
  static $columns = ['breedId', 'clientId', 'createdAt', 'dateOfBirth', 'gender', 'id', 'name', 'notes', 'speciesId', 'tenantId', 'updatedAt'] as const
  $columns = PetSchema.$columns
  @column()
  declare breedId: UUID | null
  @column()
  declare clientId: UUID | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.date()
  declare dateOfBirth: DateTime | null
  @column()
  declare gender: string | null
  @column({ isPrimary: true })
  declare id: UUID
  @column()
  declare name: string
  @column()
  declare notes: string | null
  @column()
  declare speciesId: UUID | null
  @column()
  declare tenantId: UUID | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ScheduleDaySchema extends BaseModel {
  static $columns = ['agendaId', 'createdAt', 'date', 'id', 'shifts', 'tenantId', 'updatedAt'] as const
  $columns = ScheduleDaySchema.$columns
  @column()
  declare agendaId: UUID
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.date()
  declare date: DateTime
  @column({ isPrimary: true })
  declare id: UUID
  @column()
  declare shifts: any
  @column()
  declare tenantId: UUID
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class SpeciesSchema extends BaseModel {
  static $columns = ['id', 'illustrationUrl', 'name'] as const
  $columns = SpeciesSchema.$columns
  @column({ isPrimary: true })
  declare id: UUID
  @column()
  declare illustrationUrl: string
  @column()
  declare name: string
}

export class TenantSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'name', 'phone', 'slug', 'updatedAt', 'website'] as const
  $columns = TenantSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: UUID
  @column()
  declare name: string
  @column()
  declare phone: string | null
  @column()
  declare slug: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare website: string | null
}

export class TimeOffSchema extends BaseModel {
  static $columns = ['agendaId', 'createdAt', 'description', 'end', 'endTime', 'id', 'start', 'startTime', 'tenantId', 'type', 'updatedAt'] as const
  $columns = TimeOffSchema.$columns
  @column()
  declare agendaId: UUID
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column.date()
  declare end: DateTime
  @column()
  declare endTime: string
  @column({ isPrimary: true })
  declare id: UUID
  @column.date()
  declare start: DateTime
  @column()
  declare startTime: string
  @column()
  declare tenantId: UUID
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'fullName', 'id', 'password', 'tenantId', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: UUID
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare tenantId: UUID
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class WorkingHourSchema extends BaseModel {
  static $columns = ['agendaId', 'createdAt', 'dayOfWeek', 'endTime', 'id', 'startTime', 'tenantId', 'updatedAt'] as const
  $columns = WorkingHourSchema.$columns
  @column()
  declare agendaId: UUID
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare dayOfWeek: number
  @column()
  declare endTime: string
  @column({ isPrimary: true })
  declare id: UUID
  @column()
  declare startTime: string
  @column()
  declare tenantId: UUID
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
