/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

/// <reference path="./manifest.d.ts" />
import type { InferData, InferVariants } from '@adonisjs/core/types/transformers'
import type { InferSharedProps } from '@adonisjs/inertia/types'
import type AgendasAgendaTransformer from '#app/agendas/transformers/agenda_transformer'
import type AppointmentTypesAppointmentTypeTransformer from '#app/appointment_types/transformers/appointment_type_transformer'
import type AppointmentWorkflowAppointmentStatusTransformer from '#app/appointment_workflow/transformers/appointment_status_transformer'
import type BookingAppointmentTransformer from '#app/booking/transformers/appointment_transformer'
import type IdentityUserTransformer from '#app/identity/transformers/user_transformer'
import type PatientsPatientTransformer from '#app/patients/transformers/patient_transformer'
import type SchedulingClosedDateTransformer from '#app/scheduling/transformers/closed_date_transformer'
import type SchedulingScheduleDayTransformer from '#app/scheduling/transformers/schedule_day_transformer'
import type SchedulingShiftTransformer from '#app/scheduling/transformers/shift_transformer'
import type SchedulingTimeOffTransformer from '#app/scheduling/transformers/time_off_transformer'
import type SchedulingWorkingHourTransformer from '#app/scheduling/transformers/working_hour_transformer'
import type TenantsTenantTransformer from '#app/tenants/transformers/tenant_transformer'
import type PetsBreedTransformer from '#app/pets/transformers/breed_transformer'
import type PetsSpeciesTransformer from '#app/pets/transformers/species_transformer'
import type InertiaMiddleware from '#shared/middleware/inertia_middleware'

export namespace Data {
  export namespace Agendas {
    export type Agenda = InferData<AgendasAgendaTransformer>
    export namespace Agenda {
      export type Variants = InferVariants<AgendasAgendaTransformer>
    }
  }
  export namespace AppointmentTypes {
    export type AppointmentType = InferData<AppointmentTypesAppointmentTypeTransformer>
    export namespace AppointmentType {
      export type Variants = InferVariants<AppointmentTypesAppointmentTypeTransformer>
    }
  }
  export namespace AppointmentWorkflow {
    export type AppointmentStatus = InferData<AppointmentWorkflowAppointmentStatusTransformer>
    export namespace AppointmentStatus {
      export type Variants = InferVariants<AppointmentWorkflowAppointmentStatusTransformer>
    }
  }
  export namespace Booking {
    export type Appointment = InferData<BookingAppointmentTransformer>
    export namespace Appointment {
      export type Variants = InferVariants<BookingAppointmentTransformer>
    }
  }
  export namespace Identity {
    export type User = InferData<IdentityUserTransformer>
    export namespace User {
      export type Variants = InferVariants<IdentityUserTransformer>
    }
  }
  export namespace Patients {
    export type Patient = InferData<PatientsPatientTransformer>
    export namespace Patient {
      export type Variants = InferVariants<PatientsPatientTransformer>
    }
  }
  export namespace Scheduling {
    export type ClosedDate = InferData<SchedulingClosedDateTransformer>
    export namespace ClosedDate {
      export type Variants = InferVariants<SchedulingClosedDateTransformer>
    }
    export type ScheduleDay = InferData<SchedulingScheduleDayTransformer>
    export namespace ScheduleDay {
      export type Variants = InferVariants<SchedulingScheduleDayTransformer>
    }
    export type Shift = InferData<SchedulingShiftTransformer>
    export namespace Shift {
      export type Variants = InferVariants<SchedulingShiftTransformer>
    }
    export type TimeOff = InferData<SchedulingTimeOffTransformer>
    export namespace TimeOff {
      export type Variants = InferVariants<SchedulingTimeOffTransformer>
    }
    export type WorkingHour = InferData<SchedulingWorkingHourTransformer>
    export namespace WorkingHour {
      export type Variants = InferVariants<SchedulingWorkingHourTransformer>
    }
  }
  export namespace Tenants {
    export type Tenant = InferData<TenantsTenantTransformer>
    export namespace Tenant {
      export type Variants = InferVariants<TenantsTenantTransformer>
    }
  }
  export namespace Pets {
    export type Breed = InferData<PetsBreedTransformer>
    export namespace Breed {
      export type Variants = InferVariants<PetsBreedTransformer>
    }
    export type Species = InferData<PetsSpeciesTransformer>
    export namespace Species {
      export type Variants = InferVariants<PetsSpeciesTransformer>
    }
  }
  export type SharedProps = InferSharedProps<InertiaMiddleware>
}
