/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

/// <reference path="./manifest.d.ts" />
import type { InferData, InferVariants } from '@adonisjs/core/types/transformers'
import type { InferSharedProps, InferFlashData } from '@adonisjs/inertia/types'
import type AgendasAgendaTransformer from '#app/agendas/transformers/agenda_transformer'
import type AgendasInvitationTransformer from '#app/agendas/transformers/invitation_transformer'
import type AppointmentWorkflowAppointmentStatusTransformer from '#app/appointment_workflow/transformers/appointment_status_transformer'
import type BookingAppointmentTransformer from '#app/booking/transformers/appointment_transformer'
import type ClientsClientTransformer from '#app/clients/transformers/client_transformer'
import type IdentityUserTransformer from '#app/identity/transformers/user_transformer'
import type MedicalRecordsConsultationTransformer from '#app/medical_records/transformers/consultation_transformer'
import type MedicalRecordsPrescriptionTransformer from '#app/medical_records/transformers/prescription_transformer'
import type MedicalRecordsVaccineTransformer from '#app/medical_records/transformers/vaccine_transformer'
import type PetsPetTransformer from '#app/pets/transformers/pet_transformer'
import type PetsSpeciesTransformer from '#app/pets/transformers/species_transformer'
import type SchedulingClosedDateTransformer from '#app/scheduling/transformers/closed_date_transformer'
import type SchedulingScheduleDayTransformer from '#app/scheduling/transformers/schedule_day_transformer'
import type SchedulingShiftTransformer from '#app/scheduling/transformers/shift_transformer'
import type SchedulingTimeOffTransformer from '#app/scheduling/transformers/time_off_transformer'
import type SchedulingWorkingHourTransformer from '#app/scheduling/transformers/working_hour_transformer'
import type ServicesServiceTransformer from '#app/services/transformers/service_transformer'
import type TenantsLocationTransformer from '#app/tenants/transformers/location_transformer'
import type TenantsTenantTransformer from '#app/tenants/transformers/tenant_transformer'
import type InertiaMiddleware from '#shared/middleware/inertia_middleware'

export namespace Data {
  export namespace Agendas {
    export type Agenda = InferData<AgendasAgendaTransformer>
    export namespace Agenda {
      export type Variants = InferVariants<AgendasAgendaTransformer>
    }
    export type Invitation = InferData<AgendasInvitationTransformer>
    export namespace Invitation {
      export type Variants = InferVariants<AgendasInvitationTransformer>
    }
  }
  export namespace AppointmentWorkflow {
    export type AppointmentStatus = InferData<AppointmentWorkflowAppointmentStatusTransformer>
    export namespace AppointmentStatus {
      export type Variants = InferVariants<AppointmentWorkflowAppointmentStatusTransformer>
    }
  }
  export namespace Booking {
    export type Appointment = InferData<BookingAppointmentTransformer>
    export namespace Appointment {
      export type Variants = InferVariants<BookingAppointmentTransformer>
    }
  }
  export namespace Clients {
    export type Client = InferData<ClientsClientTransformer>
    export namespace Client {
      export type Variants = InferVariants<ClientsClientTransformer>
    }
  }
  export namespace Identity {
    export type User = InferData<IdentityUserTransformer>
    export namespace User {
      export type Variants = InferVariants<IdentityUserTransformer>
    }
  }
  export namespace MedicalRecords {
    export type Consultation = InferData<MedicalRecordsConsultationTransformer>
    export namespace Consultation {
      export type Variants = InferVariants<MedicalRecordsConsultationTransformer>
    }
    export type Prescription = InferData<MedicalRecordsPrescriptionTransformer>
    export namespace Prescription {
      export type Variants = InferVariants<MedicalRecordsPrescriptionTransformer>
    }
    export type Vaccine = InferData<MedicalRecordsVaccineTransformer>
    export namespace Vaccine {
      export type Variants = InferVariants<MedicalRecordsVaccineTransformer>
    }
  }
  export namespace Pets {
    export type Pet = InferData<PetsPetTransformer>
    export namespace Pet {
      export type Variants = InferVariants<PetsPetTransformer>
    }
    export type Species = InferData<PetsSpeciesTransformer>
    export namespace Species {
      export type Variants = InferVariants<PetsSpeciesTransformer>
    }
  }
  export namespace Scheduling {
    export type ClosedDate = InferData<SchedulingClosedDateTransformer>
    export namespace ClosedDate {
      export type Variants = InferVariants<SchedulingClosedDateTransformer>
    }
    export type ScheduleDay = InferData<SchedulingScheduleDayTransformer>
    export namespace ScheduleDay {
      export type Variants = InferVariants<SchedulingScheduleDayTransformer>
    }
    export type Shift = InferData<SchedulingShiftTransformer>
    export namespace Shift {
      export type Variants = InferVariants<SchedulingShiftTransformer>
    }
    export type TimeOff = InferData<SchedulingTimeOffTransformer>
    export namespace TimeOff {
      export type Variants = InferVariants<SchedulingTimeOffTransformer>
    }
    export type WorkingHour = InferData<SchedulingWorkingHourTransformer>
    export namespace WorkingHour {
      export type Variants = InferVariants<SchedulingWorkingHourTransformer>
    }
  }
  export namespace Services {
    export type Service = InferData<ServicesServiceTransformer>
    export namespace Service {
      export type Variants = InferVariants<ServicesServiceTransformer>
    }
  }
  export namespace Tenants {
    export type Location = InferData<TenantsLocationTransformer>
    export namespace Location {
      export type Variants = InferVariants<TenantsLocationTransformer>
    }
    export type Tenant = InferData<TenantsTenantTransformer>
    export namespace Tenant {
      export type Variants = InferVariants<TenantsTenantTransformer>
    }
  }
  export type SharedProps = InferSharedProps<InertiaMiddleware>
  export type FlashMessages = InferFlashData<InertiaMiddleware>
}
