/* eslint-disable prettier/prettier */
import type { AdonisEndpoint } from '@tuyau/core/types'
import type { Registry } from './schema.d.ts'
import type { ApiDefinition } from './tree.d.ts'

const placeholder: any = {}

const routes = {
  'dashboard.render': {
    methods: ["GET","HEAD"],
    pattern: '/dashboard',
    tokens: [{"old":"/dashboard","type":0,"val":"dashboard","end":""}],
    types: placeholder as Registry['dashboard.render']['types'],
  },
  'show_settings.render': {
    methods: ["GET","HEAD"],
    pattern: '/settings',
    tokens: [{"old":"/settings","type":0,"val":"settings","end":""}],
    types: placeholder as Registry['show_settings.render']['types'],
  },
  'signup.render': {
    methods: ["GET","HEAD"],
    pattern: '/signup',
    tokens: [{"old":"/signup","type":0,"val":"signup","end":""}],
    types: placeholder as Registry['signup.render']['types'],
  },
  'signup.execute': {
    methods: ["POST"],
    pattern: '/signup',
    tokens: [{"old":"/signup","type":0,"val":"signup","end":""}],
    types: placeholder as Registry['signup.execute']['types'],
  },
  'login.render': {
    methods: ["GET","HEAD"],
    pattern: '/login',
    tokens: [{"old":"/login","type":0,"val":"login","end":""}],
    types: placeholder as Registry['login.render']['types'],
  },
  'login.execute': {
    methods: ["POST"],
    pattern: '/login',
    tokens: [{"old":"/login","type":0,"val":"login","end":""}],
    types: placeholder as Registry['login.execute']['types'],
  },
  'forgot_password.render': {
    methods: ["GET","HEAD"],
    pattern: '/forgot-password',
    tokens: [{"old":"/forgot-password","type":0,"val":"forgot-password","end":""}],
    types: placeholder as Registry['forgot_password.render']['types'],
  },
  'forgot_password.execute': {
    methods: ["POST"],
    pattern: '/forgot-password',
    tokens: [{"old":"/forgot-password","type":0,"val":"forgot-password","end":""}],
    types: placeholder as Registry['forgot_password.execute']['types'],
  },
  'reset_password.render': {
    methods: ["GET","HEAD"],
    pattern: '/reset-password/:token',
    tokens: [{"old":"/reset-password/:token","type":0,"val":"reset-password","end":""},{"old":"/reset-password/:token","type":1,"val":"token","end":""}],
    types: placeholder as Registry['reset_password.render']['types'],
  },
  'reset_password.execute': {
    methods: ["POST"],
    pattern: '/reset-password',
    tokens: [{"old":"/reset-password","type":0,"val":"reset-password","end":""}],
    types: placeholder as Registry['reset_password.execute']['types'],
  },
  'logout.execute': {
    methods: ["POST"],
    pattern: '/logout',
    tokens: [{"old":"/logout","type":0,"val":"logout","end":""}],
    types: placeholder as Registry['logout.execute']['types'],
  },
  'show_account.render': {
    methods: ["GET","HEAD"],
    pattern: '/user/account',
    tokens: [{"old":"/user/account","type":0,"val":"user","end":""},{"old":"/user/account","type":0,"val":"account","end":""}],
    types: placeholder as Registry['show_account.render']['types'],
  },
  'update_account.execute': {
    methods: ["PUT"],
    pattern: '/user/account',
    tokens: [{"old":"/user/account","type":0,"val":"user","end":""},{"old":"/user/account","type":0,"val":"account","end":""}],
    types: placeholder as Registry['update_account.execute']['types'],
  },
  'update_password.render': {
    methods: ["GET","HEAD"],
    pattern: '/user/account/password',
    tokens: [{"old":"/user/account/password","type":0,"val":"user","end":""},{"old":"/user/account/password","type":0,"val":"account","end":""},{"old":"/user/account/password","type":0,"val":"password","end":""}],
    types: placeholder as Registry['update_password.render']['types'],
  },
  'update_password.execute': {
    methods: ["PUT"],
    pattern: '/user/account/password',
    tokens: [{"old":"/user/account/password","type":0,"val":"user","end":""},{"old":"/user/account/password","type":0,"val":"account","end":""},{"old":"/user/account/password","type":0,"val":"password","end":""}],
    types: placeholder as Registry['update_password.execute']['types'],
  },
  'list_agendas.render': {
    methods: ["GET","HEAD"],
    pattern: '/settings/agendas',
    tokens: [{"old":"/settings/agendas","type":0,"val":"settings","end":""},{"old":"/settings/agendas","type":0,"val":"agendas","end":""}],
    types: placeholder as Registry['list_agendas.render']['types'],
  },
  'create_agenda.render': {
    methods: ["GET","HEAD"],
    pattern: '/settings/agendas/new',
    tokens: [{"old":"/settings/agendas/new","type":0,"val":"settings","end":""},{"old":"/settings/agendas/new","type":0,"val":"agendas","end":""},{"old":"/settings/agendas/new","type":0,"val":"new","end":""}],
    types: placeholder as Registry['create_agenda.render']['types'],
  },
  'create_agenda.execute': {
    methods: ["POST"],
    pattern: '/settings/agendas',
    tokens: [{"old":"/settings/agendas","type":0,"val":"settings","end":""},{"old":"/settings/agendas","type":0,"val":"agendas","end":""}],
    types: placeholder as Registry['create_agenda.execute']['types'],
  },
  'update_agenda.render': {
    methods: ["GET","HEAD"],
    pattern: '/settings/agendas/edit/:id',
    tokens: [{"old":"/settings/agendas/edit/:id","type":0,"val":"settings","end":""},{"old":"/settings/agendas/edit/:id","type":0,"val":"agendas","end":""},{"old":"/settings/agendas/edit/:id","type":0,"val":"edit","end":""},{"old":"/settings/agendas/edit/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['update_agenda.render']['types'],
  },
  'update_agenda.execute': {
    methods: ["PUT"],
    pattern: '/settings/agendas/:id',
    tokens: [{"old":"/settings/agendas/:id","type":0,"val":"settings","end":""},{"old":"/settings/agendas/:id","type":0,"val":"agendas","end":""},{"old":"/settings/agendas/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['update_agenda.execute']['types'],
  },
  'delete_agenda.execute': {
    methods: ["DELETE"],
    pattern: '/settings/agendas/:id',
    tokens: [{"old":"/settings/agendas/:id","type":0,"val":"settings","end":""},{"old":"/settings/agendas/:id","type":0,"val":"agendas","end":""},{"old":"/settings/agendas/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['delete_agenda.execute']['types'],
  },
  'list_services.render': {
    methods: ["GET","HEAD"],
    pattern: '/settings/services',
    tokens: [{"old":"/settings/services","type":0,"val":"settings","end":""},{"old":"/settings/services","type":0,"val":"services","end":""}],
    types: placeholder as Registry['list_services.render']['types'],
  },
  'create_service.render': {
    methods: ["GET","HEAD"],
    pattern: '/settings/services/new',
    tokens: [{"old":"/settings/services/new","type":0,"val":"settings","end":""},{"old":"/settings/services/new","type":0,"val":"services","end":""},{"old":"/settings/services/new","type":0,"val":"new","end":""}],
    types: placeholder as Registry['create_service.render']['types'],
  },
  'create_service.execute': {
    methods: ["POST"],
    pattern: '/settings/services',
    tokens: [{"old":"/settings/services","type":0,"val":"settings","end":""},{"old":"/settings/services","type":0,"val":"services","end":""}],
    types: placeholder as Registry['create_service.execute']['types'],
  },
  'update_service.render': {
    methods: ["GET","HEAD"],
    pattern: '/settings/services/edit/:id',
    tokens: [{"old":"/settings/services/edit/:id","type":0,"val":"settings","end":""},{"old":"/settings/services/edit/:id","type":0,"val":"services","end":""},{"old":"/settings/services/edit/:id","type":0,"val":"edit","end":""},{"old":"/settings/services/edit/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['update_service.render']['types'],
  },
  'update_service.execute': {
    methods: ["PUT"],
    pattern: '/settings/services/:id',
    tokens: [{"old":"/settings/services/:id","type":0,"val":"settings","end":""},{"old":"/settings/services/:id","type":0,"val":"services","end":""},{"old":"/settings/services/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['update_service.execute']['types'],
  },
  'delete_service.execute': {
    methods: ["DELETE"],
    pattern: '/settings/services/:id',
    tokens: [{"old":"/settings/services/:id","type":0,"val":"settings","end":""},{"old":"/settings/services/:id","type":0,"val":"services","end":""},{"old":"/settings/services/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['delete_service.execute']['types'],
  },
  'list_appointment_statuses.render': {
    methods: ["GET","HEAD"],
    pattern: '/settings/statuses',
    tokens: [{"old":"/settings/statuses","type":0,"val":"settings","end":""},{"old":"/settings/statuses","type":0,"val":"statuses","end":""}],
    types: placeholder as Registry['list_appointment_statuses.render']['types'],
  },
  'create_appointment_status.render': {
    methods: ["GET","HEAD"],
    pattern: '/settings/statuses/new',
    tokens: [{"old":"/settings/statuses/new","type":0,"val":"settings","end":""},{"old":"/settings/statuses/new","type":0,"val":"statuses","end":""},{"old":"/settings/statuses/new","type":0,"val":"new","end":""}],
    types: placeholder as Registry['create_appointment_status.render']['types'],
  },
  'create_appointment_status.execute': {
    methods: ["POST"],
    pattern: '/settings/statuses',
    tokens: [{"old":"/settings/statuses","type":0,"val":"settings","end":""},{"old":"/settings/statuses","type":0,"val":"statuses","end":""}],
    types: placeholder as Registry['create_appointment_status.execute']['types'],
  },
  'update_appointment_status.render': {
    methods: ["GET","HEAD"],
    pattern: '/settings/statuses/:id/edit',
    tokens: [{"old":"/settings/statuses/:id/edit","type":0,"val":"settings","end":""},{"old":"/settings/statuses/:id/edit","type":0,"val":"statuses","end":""},{"old":"/settings/statuses/:id/edit","type":1,"val":"id","end":""},{"old":"/settings/statuses/:id/edit","type":0,"val":"edit","end":""}],
    types: placeholder as Registry['update_appointment_status.render']['types'],
  },
  'update_appointment_status.execute': {
    methods: ["PUT"],
    pattern: '/settings/statuses/:id',
    tokens: [{"old":"/settings/statuses/:id","type":0,"val":"settings","end":""},{"old":"/settings/statuses/:id","type":0,"val":"statuses","end":""},{"old":"/settings/statuses/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['update_appointment_status.execute']['types'],
  },
  'move_appointment_status.execute': {
    methods: ["POST"],
    pattern: '/settings/statuses/:id/move',
    tokens: [{"old":"/settings/statuses/:id/move","type":0,"val":"settings","end":""},{"old":"/settings/statuses/:id/move","type":0,"val":"statuses","end":""},{"old":"/settings/statuses/:id/move","type":1,"val":"id","end":""},{"old":"/settings/statuses/:id/move","type":0,"val":"move","end":""}],
    types: placeholder as Registry['move_appointment_status.execute']['types'],
  },
  'delete_appointment_status.execute': {
    methods: ["DELETE"],
    pattern: '/settings/statuses/:id',
    tokens: [{"old":"/settings/statuses/:id","type":0,"val":"settings","end":""},{"old":"/settings/statuses/:id","type":0,"val":"statuses","end":""},{"old":"/settings/statuses/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['delete_appointment_status.execute']['types'],
  },
  'list_clients.render': {
    methods: ["GET","HEAD"],
    pattern: '/clients',
    tokens: [{"old":"/clients","type":0,"val":"clients","end":""}],
    types: placeholder as Registry['list_clients.render']['types'],
  },
  'create_client.render': {
    methods: ["GET","HEAD"],
    pattern: '/clients/new',
    tokens: [{"old":"/clients/new","type":0,"val":"clients","end":""},{"old":"/clients/new","type":0,"val":"new","end":""}],
    types: placeholder as Registry['create_client.render']['types'],
  },
  'create_client.execute': {
    methods: ["POST"],
    pattern: '/clients',
    tokens: [{"old":"/clients","type":0,"val":"clients","end":""}],
    types: placeholder as Registry['create_client.execute']['types'],
  },
  'update_client.render': {
    methods: ["GET","HEAD"],
    pattern: '/clients/edit/:id',
    tokens: [{"old":"/clients/edit/:id","type":0,"val":"clients","end":""},{"old":"/clients/edit/:id","type":0,"val":"edit","end":""},{"old":"/clients/edit/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['update_client.render']['types'],
  },
  'get_client.render': {
    methods: ["GET","HEAD"],
    pattern: '/clients/:id',
    tokens: [{"old":"/clients/:id","type":0,"val":"clients","end":""},{"old":"/clients/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['get_client.render']['types'],
  },
  'update_client.execute': {
    methods: ["PUT"],
    pattern: '/clients/:id',
    tokens: [{"old":"/clients/:id","type":0,"val":"clients","end":""},{"old":"/clients/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['update_client.execute']['types'],
  },
  'delete_client.execute': {
    methods: ["DELETE"],
    pattern: '/clients/:id',
    tokens: [{"old":"/clients/:id","type":0,"val":"clients","end":""},{"old":"/clients/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['delete_client.execute']['types'],
  },
  'list_clients.api': {
    methods: ["GET","HEAD"],
    pattern: '/api/clients',
    tokens: [{"old":"/api/clients","type":0,"val":"api","end":""},{"old":"/api/clients","type":0,"val":"clients","end":""}],
    types: placeholder as Registry['list_clients.api']['types'],
  },
  'get_client.api': {
    methods: ["GET","HEAD"],
    pattern: '/api/clients/:id',
    tokens: [{"old":"/api/clients/:id","type":0,"val":"api","end":""},{"old":"/api/clients/:id","type":0,"val":"clients","end":""},{"old":"/api/clients/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['get_client.api']['types'],
  },
  'show_tenant.render': {
    methods: ["GET","HEAD"],
    pattern: '/settings/tenant',
    tokens: [{"old":"/settings/tenant","type":0,"val":"settings","end":""},{"old":"/settings/tenant","type":0,"val":"tenant","end":""}],
    types: placeholder as Registry['show_tenant.render']['types'],
  },
  'update_tenant.render': {
    methods: ["GET","HEAD"],
    pattern: '/settings/tenant/edit',
    tokens: [{"old":"/settings/tenant/edit","type":0,"val":"settings","end":""},{"old":"/settings/tenant/edit","type":0,"val":"tenant","end":""},{"old":"/settings/tenant/edit","type":0,"val":"edit","end":""}],
    types: placeholder as Registry['update_tenant.render']['types'],
  },
  'update_tenant.execute': {
    methods: ["PUT"],
    pattern: '/settings/tenant',
    tokens: [{"old":"/settings/tenant","type":0,"val":"settings","end":""},{"old":"/settings/tenant","type":0,"val":"tenant","end":""}],
    types: placeholder as Registry['update_tenant.execute']['types'],
  },
  'update_location.render': {
    methods: ["GET","HEAD"],
    pattern: '/settings/location/edit',
    tokens: [{"old":"/settings/location/edit","type":0,"val":"settings","end":""},{"old":"/settings/location/edit","type":0,"val":"location","end":""},{"old":"/settings/location/edit","type":0,"val":"edit","end":""}],
    types: placeholder as Registry['update_location.render']['types'],
  },
  'update_location.execute': {
    methods: ["PUT"],
    pattern: '/settings/location',
    tokens: [{"old":"/settings/location","type":0,"val":"settings","end":""},{"old":"/settings/location","type":0,"val":"location","end":""}],
    types: placeholder as Registry['update_location.execute']['types'],
  },
  'book_appointment.render': {
    methods: ["GET","HEAD"],
    pattern: '/:slug/booking',
    tokens: [{"old":"/:slug/booking","type":1,"val":"slug","end":""},{"old":"/:slug/booking","type":0,"val":"booking","end":""}],
    types: placeholder as Registry['book_appointment.render']['types'],
  },
  'book_appointment.execute': {
    methods: ["POST"],
    pattern: '/:slug/booking',
    tokens: [{"old":"/:slug/booking","type":1,"val":"slug","end":""},{"old":"/:slug/booking","type":0,"val":"booking","end":""}],
    types: placeholder as Registry['book_appointment.execute']['types'],
  },
  'confirm_appointment.render': {
    methods: ["GET","HEAD"],
    pattern: '/:slug/booking/:appointmentId/confirm',
    tokens: [{"old":"/:slug/booking/:appointmentId/confirm","type":1,"val":"slug","end":""},{"old":"/:slug/booking/:appointmentId/confirm","type":0,"val":"booking","end":""},{"old":"/:slug/booking/:appointmentId/confirm","type":1,"val":"appointmentId","end":""},{"old":"/:slug/booking/:appointmentId/confirm","type":0,"val":"confirm","end":""}],
    types: placeholder as Registry['confirm_appointment.render']['types'],
  },
  'show_calendar.render': {
    methods: ["GET","HEAD"],
    pattern: '/calendar',
    tokens: [{"old":"/calendar","type":0,"val":"calendar","end":""}],
    types: placeholder as Registry['show_calendar.render']['types'],
  },
  'list_appointments.render': {
    methods: ["GET","HEAD"],
    pattern: '/appointments',
    tokens: [{"old":"/appointments","type":0,"val":"appointments","end":""}],
    types: placeholder as Registry['list_appointments.render']['types'],
  },
  'create_appointment.render': {
    methods: ["GET","HEAD"],
    pattern: '/appointments/new',
    tokens: [{"old":"/appointments/new","type":0,"val":"appointments","end":""},{"old":"/appointments/new","type":0,"val":"new","end":""}],
    types: placeholder as Registry['create_appointment.render']['types'],
  },
  'create_appointment.execute': {
    methods: ["POST"],
    pattern: '/appointments',
    tokens: [{"old":"/appointments","type":0,"val":"appointments","end":""}],
    types: placeholder as Registry['create_appointment.execute']['types'],
  },
  'update_appointment.render': {
    methods: ["GET","HEAD"],
    pattern: '/appointments/edit/:id',
    tokens: [{"old":"/appointments/edit/:id","type":0,"val":"appointments","end":""},{"old":"/appointments/edit/:id","type":0,"val":"edit","end":""},{"old":"/appointments/edit/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['update_appointment.render']['types'],
  },
  'update_appointment.execute': {
    methods: ["PUT"],
    pattern: '/appointments/:id',
    tokens: [{"old":"/appointments/:id","type":0,"val":"appointments","end":""},{"old":"/appointments/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['update_appointment.execute']['types'],
  },
  'change_appointment_status.execute': {
    methods: ["PATCH"],
    pattern: '/appointments/:id/status',
    tokens: [{"old":"/appointments/:id/status","type":0,"val":"appointments","end":""},{"old":"/appointments/:id/status","type":1,"val":"id","end":""},{"old":"/appointments/:id/status","type":0,"val":"status","end":""}],
    types: placeholder as Registry['change_appointment_status.execute']['types'],
  },
  'booking_link.render': {
    methods: ["GET","HEAD"],
    pattern: '/settings/booking-link',
    tokens: [{"old":"/settings/booking-link","type":0,"val":"settings","end":""},{"old":"/settings/booking-link","type":0,"val":"booking-link","end":""}],
    types: placeholder as Registry['booking_link.render']['types'],
  },
  'list_shifts.render': {
    methods: ["GET","HEAD"],
    pattern: '/settings/shifts',
    tokens: [{"old":"/settings/shifts","type":0,"val":"settings","end":""},{"old":"/settings/shifts","type":0,"val":"shifts","end":""}],
    types: placeholder as Registry['list_shifts.render']['types'],
  },
  'create_closed_date.render': {
    methods: ["GET","HEAD"],
    pattern: '/settings/closed-dates/new',
    tokens: [{"old":"/settings/closed-dates/new","type":0,"val":"settings","end":""},{"old":"/settings/closed-dates/new","type":0,"val":"closed-dates","end":""},{"old":"/settings/closed-dates/new","type":0,"val":"new","end":""}],
    types: placeholder as Registry['create_closed_date.render']['types'],
  },
  'create_closed_date.execute': {
    methods: ["POST"],
    pattern: '/settings/closed-dates',
    tokens: [{"old":"/settings/closed-dates","type":0,"val":"settings","end":""},{"old":"/settings/closed-dates","type":0,"val":"closed-dates","end":""}],
    types: placeholder as Registry['create_closed_date.execute']['types'],
  },
  'update_closed_date.render': {
    methods: ["GET","HEAD"],
    pattern: '/settings/closed-dates/edit/:id',
    tokens: [{"old":"/settings/closed-dates/edit/:id","type":0,"val":"settings","end":""},{"old":"/settings/closed-dates/edit/:id","type":0,"val":"closed-dates","end":""},{"old":"/settings/closed-dates/edit/:id","type":0,"val":"edit","end":""},{"old":"/settings/closed-dates/edit/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['update_closed_date.render']['types'],
  },
  'update_closed_date.execute': {
    methods: ["PUT"],
    pattern: '/settings/closed-dates/:id',
    tokens: [{"old":"/settings/closed-dates/:id","type":0,"val":"settings","end":""},{"old":"/settings/closed-dates/:id","type":0,"val":"closed-dates","end":""},{"old":"/settings/closed-dates/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['update_closed_date.execute']['types'],
  },
  'delete_closed_date.execute': {
    methods: ["DELETE"],
    pattern: '/settings/closed-dates/:id',
    tokens: [{"old":"/settings/closed-dates/:id","type":0,"val":"settings","end":""},{"old":"/settings/closed-dates/:id","type":0,"val":"closed-dates","end":""},{"old":"/settings/closed-dates/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['delete_closed_date.execute']['types'],
  },
  'create_time_off.render': {
    methods: ["GET","HEAD"],
    pattern: '/settings/time-offs/new',
    tokens: [{"old":"/settings/time-offs/new","type":0,"val":"settings","end":""},{"old":"/settings/time-offs/new","type":0,"val":"time-offs","end":""},{"old":"/settings/time-offs/new","type":0,"val":"new","end":""}],
    types: placeholder as Registry['create_time_off.render']['types'],
  },
  'create_time_off.execute': {
    methods: ["POST"],
    pattern: '/settings/time-offs',
    tokens: [{"old":"/settings/time-offs","type":0,"val":"settings","end":""},{"old":"/settings/time-offs","type":0,"val":"time-offs","end":""}],
    types: placeholder as Registry['create_time_off.execute']['types'],
  },
  'update_time_off.render': {
    methods: ["GET","HEAD"],
    pattern: '/settings/time-offs/edit/:id',
    tokens: [{"old":"/settings/time-offs/edit/:id","type":0,"val":"settings","end":""},{"old":"/settings/time-offs/edit/:id","type":0,"val":"time-offs","end":""},{"old":"/settings/time-offs/edit/:id","type":0,"val":"edit","end":""},{"old":"/settings/time-offs/edit/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['update_time_off.render']['types'],
  },
  'update_time_off.execute': {
    methods: ["PUT"],
    pattern: '/settings/time-offs/:id',
    tokens: [{"old":"/settings/time-offs/:id","type":0,"val":"settings","end":""},{"old":"/settings/time-offs/:id","type":0,"val":"time-offs","end":""},{"old":"/settings/time-offs/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['update_time_off.execute']['types'],
  },
  'delete_time_off.execute': {
    methods: ["DELETE"],
    pattern: '/settings/time-offs/:id',
    tokens: [{"old":"/settings/time-offs/:id","type":0,"val":"settings","end":""},{"old":"/settings/time-offs/:id","type":0,"val":"time-offs","end":""},{"old":"/settings/time-offs/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['delete_time_off.execute']['types'],
  },
  'update_working_hours.render': {
    methods: ["GET","HEAD"],
    pattern: '/settings/working-hours/:agendaId',
    tokens: [{"old":"/settings/working-hours/:agendaId","type":0,"val":"settings","end":""},{"old":"/settings/working-hours/:agendaId","type":0,"val":"working-hours","end":""},{"old":"/settings/working-hours/:agendaId","type":1,"val":"agendaId","end":""}],
    types: placeholder as Registry['update_working_hours.render']['types'],
  },
  'update_working_hours.execute': {
    methods: ["PUT"],
    pattern: '/settings/working-hours/:agendaId',
    tokens: [{"old":"/settings/working-hours/:agendaId","type":0,"val":"settings","end":""},{"old":"/settings/working-hours/:agendaId","type":0,"val":"working-hours","end":""},{"old":"/settings/working-hours/:agendaId","type":1,"val":"agendaId","end":""}],
    types: placeholder as Registry['update_working_hours.execute']['types'],
  },
  'create_schedule_day.render': {
    methods: ["GET","HEAD"],
    pattern: '/settings/schedule-days/new',
    tokens: [{"old":"/settings/schedule-days/new","type":0,"val":"settings","end":""},{"old":"/settings/schedule-days/new","type":0,"val":"schedule-days","end":""},{"old":"/settings/schedule-days/new","type":0,"val":"new","end":""}],
    types: placeholder as Registry['create_schedule_day.render']['types'],
  },
  'create_schedule_day.execute': {
    methods: ["POST"],
    pattern: '/settings/schedule-days',
    tokens: [{"old":"/settings/schedule-days","type":0,"val":"settings","end":""},{"old":"/settings/schedule-days","type":0,"val":"schedule-days","end":""}],
    types: placeholder as Registry['create_schedule_day.execute']['types'],
  },
  'update_schedule_day.render': {
    methods: ["GET","HEAD"],
    pattern: '/settings/schedule-days/edit/:id',
    tokens: [{"old":"/settings/schedule-days/edit/:id","type":0,"val":"settings","end":""},{"old":"/settings/schedule-days/edit/:id","type":0,"val":"schedule-days","end":""},{"old":"/settings/schedule-days/edit/:id","type":0,"val":"edit","end":""},{"old":"/settings/schedule-days/edit/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['update_schedule_day.render']['types'],
  },
  'update_schedule_day.execute': {
    methods: ["PUT"],
    pattern: '/settings/schedule-days/:id',
    tokens: [{"old":"/settings/schedule-days/:id","type":0,"val":"settings","end":""},{"old":"/settings/schedule-days/:id","type":0,"val":"schedule-days","end":""},{"old":"/settings/schedule-days/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['update_schedule_day.execute']['types'],
  },
  'delete_schedule_day.execute': {
    methods: ["DELETE"],
    pattern: '/settings/schedule-days/:id',
    tokens: [{"old":"/settings/schedule-days/:id","type":0,"val":"settings","end":""},{"old":"/settings/schedule-days/:id","type":0,"val":"schedule-days","end":""},{"old":"/settings/schedule-days/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['delete_schedule_day.execute']['types'],
  },
  'get_bookable_days.render': {
    methods: ["GET","HEAD"],
    pattern: '/api/bookable-days',
    tokens: [{"old":"/api/bookable-days","type":0,"val":"api","end":""},{"old":"/api/bookable-days","type":0,"val":"bookable-days","end":""}],
    types: placeholder as Registry['get_bookable_days.render']['types'],
  },
  'get_bookable_slots.render': {
    methods: ["GET","HEAD"],
    pattern: '/api/bookable-slots',
    tokens: [{"old":"/api/bookable-slots","type":0,"val":"api","end":""},{"old":"/api/bookable-slots","type":0,"val":"bookable-slots","end":""}],
    types: placeholder as Registry['get_bookable_slots.render']['types'],
  },
  'search.render': {
    methods: ["GET","HEAD"],
    pattern: '/search',
    tokens: [{"old":"/search","type":0,"val":"search","end":""}],
    types: placeholder as Registry['search.render']['types'],
  },
  'list_pets.render': {
    methods: ["GET","HEAD"],
    pattern: '/pets',
    tokens: [{"old":"/pets","type":0,"val":"pets","end":""}],
    types: placeholder as Registry['list_pets.render']['types'],
  },
  'create_pet.render': {
    methods: ["GET","HEAD"],
    pattern: '/pets/new',
    tokens: [{"old":"/pets/new","type":0,"val":"pets","end":""},{"old":"/pets/new","type":0,"val":"new","end":""}],
    types: placeholder as Registry['create_pet.render']['types'],
  },
  'create_pet.execute': {
    methods: ["POST"],
    pattern: '/pets',
    tokens: [{"old":"/pets","type":0,"val":"pets","end":""}],
    types: placeholder as Registry['create_pet.execute']['types'],
  },
  'get_pet.render': {
    methods: ["GET","HEAD"],
    pattern: '/pets/:id',
    tokens: [{"old":"/pets/:id","type":0,"val":"pets","end":""},{"old":"/pets/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['get_pet.render']['types'],
  },
  'update_pet.render': {
    methods: ["GET","HEAD"],
    pattern: '/pets/edit/:id',
    tokens: [{"old":"/pets/edit/:id","type":0,"val":"pets","end":""},{"old":"/pets/edit/:id","type":0,"val":"edit","end":""},{"old":"/pets/edit/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['update_pet.render']['types'],
  },
  'update_pet.execute': {
    methods: ["PUT"],
    pattern: '/pets/:id',
    tokens: [{"old":"/pets/:id","type":0,"val":"pets","end":""},{"old":"/pets/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['update_pet.execute']['types'],
  },
  'delete_pet.execute': {
    methods: ["DELETE"],
    pattern: '/pets/:id',
    tokens: [{"old":"/pets/:id","type":0,"val":"pets","end":""},{"old":"/pets/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['delete_pet.execute']['types'],
  },
  'list_pets.api': {
    methods: ["GET","HEAD"],
    pattern: '/api/pets',
    tokens: [{"old":"/api/pets","type":0,"val":"api","end":""},{"old":"/api/pets","type":0,"val":"pets","end":""}],
    types: placeholder as Registry['list_pets.api']['types'],
  },
  'get_pet.api': {
    methods: ["GET","HEAD"],
    pattern: '/api/pets/:id',
    tokens: [{"old":"/api/pets/:id","type":0,"val":"api","end":""},{"old":"/api/pets/:id","type":0,"val":"pets","end":""},{"old":"/api/pets/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['get_pet.api']['types'],
  },
  'list_consultations.render': {
    methods: ["GET","HEAD"],
    pattern: '/consultations',
    tokens: [{"old":"/consultations","type":0,"val":"consultations","end":""}],
    types: placeholder as Registry['list_consultations.render']['types'],
  },
  'create_consultation.render': {
    methods: ["GET","HEAD"],
    pattern: '/pets/:petId/consultations/new',
    tokens: [{"old":"/pets/:petId/consultations/new","type":0,"val":"pets","end":""},{"old":"/pets/:petId/consultations/new","type":1,"val":"petId","end":""},{"old":"/pets/:petId/consultations/new","type":0,"val":"consultations","end":""},{"old":"/pets/:petId/consultations/new","type":0,"val":"new","end":""}],
    types: placeholder as Registry['create_consultation.render']['types'],
  },
  'create_consultation.execute': {
    methods: ["POST"],
    pattern: '/pets/:petId/consultations',
    tokens: [{"old":"/pets/:petId/consultations","type":0,"val":"pets","end":""},{"old":"/pets/:petId/consultations","type":1,"val":"petId","end":""},{"old":"/pets/:petId/consultations","type":0,"val":"consultations","end":""}],
    types: placeholder as Registry['create_consultation.execute']['types'],
  },
  'update_consultation.render': {
    methods: ["GET","HEAD"],
    pattern: '/pets/:petId/consultations/:id/edit',
    tokens: [{"old":"/pets/:petId/consultations/:id/edit","type":0,"val":"pets","end":""},{"old":"/pets/:petId/consultations/:id/edit","type":1,"val":"petId","end":""},{"old":"/pets/:petId/consultations/:id/edit","type":0,"val":"consultations","end":""},{"old":"/pets/:petId/consultations/:id/edit","type":1,"val":"id","end":""},{"old":"/pets/:petId/consultations/:id/edit","type":0,"val":"edit","end":""}],
    types: placeholder as Registry['update_consultation.render']['types'],
  },
  'update_consultation.execute': {
    methods: ["PUT"],
    pattern: '/pets/:petId/consultations/:id',
    tokens: [{"old":"/pets/:petId/consultations/:id","type":0,"val":"pets","end":""},{"old":"/pets/:petId/consultations/:id","type":1,"val":"petId","end":""},{"old":"/pets/:petId/consultations/:id","type":0,"val":"consultations","end":""},{"old":"/pets/:petId/consultations/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['update_consultation.execute']['types'],
  },
  'create_vaccine.render': {
    methods: ["GET","HEAD"],
    pattern: '/pets/:petId/vaccines/new',
    tokens: [{"old":"/pets/:petId/vaccines/new","type":0,"val":"pets","end":""},{"old":"/pets/:petId/vaccines/new","type":1,"val":"petId","end":""},{"old":"/pets/:petId/vaccines/new","type":0,"val":"vaccines","end":""},{"old":"/pets/:petId/vaccines/new","type":0,"val":"new","end":""}],
    types: placeholder as Registry['create_vaccine.render']['types'],
  },
  'create_vaccine.execute': {
    methods: ["POST"],
    pattern: '/pets/:petId/vaccines',
    tokens: [{"old":"/pets/:petId/vaccines","type":0,"val":"pets","end":""},{"old":"/pets/:petId/vaccines","type":1,"val":"petId","end":""},{"old":"/pets/:petId/vaccines","type":0,"val":"vaccines","end":""}],
    types: placeholder as Registry['create_vaccine.execute']['types'],
  },
  'update_vaccine.render': {
    methods: ["GET","HEAD"],
    pattern: '/pets/:petId/vaccines/:id',
    tokens: [{"old":"/pets/:petId/vaccines/:id","type":0,"val":"pets","end":""},{"old":"/pets/:petId/vaccines/:id","type":1,"val":"petId","end":""},{"old":"/pets/:petId/vaccines/:id","type":0,"val":"vaccines","end":""},{"old":"/pets/:petId/vaccines/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['update_vaccine.render']['types'],
  },
  'update_vaccine.execute': {
    methods: ["PUT"],
    pattern: '/pets/:petId/vaccines/:id',
    tokens: [{"old":"/pets/:petId/vaccines/:id","type":0,"val":"pets","end":""},{"old":"/pets/:petId/vaccines/:id","type":1,"val":"petId","end":""},{"old":"/pets/:petId/vaccines/:id","type":0,"val":"vaccines","end":""},{"old":"/pets/:petId/vaccines/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['update_vaccine.execute']['types'],
  },
  'create_prescription.render': {
    methods: ["GET","HEAD"],
    pattern: '/pets/:petId/prescriptions/new',
    tokens: [{"old":"/pets/:petId/prescriptions/new","type":0,"val":"pets","end":""},{"old":"/pets/:petId/prescriptions/new","type":1,"val":"petId","end":""},{"old":"/pets/:petId/prescriptions/new","type":0,"val":"prescriptions","end":""},{"old":"/pets/:petId/prescriptions/new","type":0,"val":"new","end":""}],
    types: placeholder as Registry['create_prescription.render']['types'],
  },
  'create_prescription.execute': {
    methods: ["POST"],
    pattern: '/pets/:petId/prescriptions',
    tokens: [{"old":"/pets/:petId/prescriptions","type":0,"val":"pets","end":""},{"old":"/pets/:petId/prescriptions","type":1,"val":"petId","end":""},{"old":"/pets/:petId/prescriptions","type":0,"val":"prescriptions","end":""}],
    types: placeholder as Registry['create_prescription.execute']['types'],
  },
  'update_prescription.render': {
    methods: ["GET","HEAD"],
    pattern: '/pets/:petId/prescriptions/:id',
    tokens: [{"old":"/pets/:petId/prescriptions/:id","type":0,"val":"pets","end":""},{"old":"/pets/:petId/prescriptions/:id","type":1,"val":"petId","end":""},{"old":"/pets/:petId/prescriptions/:id","type":0,"val":"prescriptions","end":""},{"old":"/pets/:petId/prescriptions/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['update_prescription.render']['types'],
  },
  'update_prescription.execute': {
    methods: ["PUT"],
    pattern: '/pets/:petId/prescriptions/:id',
    tokens: [{"old":"/pets/:petId/prescriptions/:id","type":0,"val":"pets","end":""},{"old":"/pets/:petId/prescriptions/:id","type":1,"val":"petId","end":""},{"old":"/pets/:petId/prescriptions/:id","type":0,"val":"prescriptions","end":""},{"old":"/pets/:petId/prescriptions/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['update_prescription.execute']['types'],
  },
  'show_onboarding.render': {
    methods: ["GET","HEAD"],
    pattern: '/onboarding',
    tokens: [{"old":"/onboarding","type":0,"val":"onboarding","end":""}],
    types: placeholder as Registry['show_onboarding.render']['types'],
  },
  'update_onboarding.execute': {
    methods: ["POST"],
    pattern: '/onboarding',
    tokens: [{"old":"/onboarding","type":0,"val":"onboarding","end":""}],
    types: placeholder as Registry['update_onboarding.execute']['types'],
  },
  'event_stream': {
    methods: ["GET","HEAD"],
    pattern: '/__transmit/events',
    tokens: [{"old":"/__transmit/events","type":0,"val":"__transmit","end":""},{"old":"/__transmit/events","type":0,"val":"events","end":""}],
    types: placeholder as Registry['event_stream']['types'],
  },
  'subscribe': {
    methods: ["POST"],
    pattern: '/__transmit/subscribe',
    tokens: [{"old":"/__transmit/subscribe","type":0,"val":"__transmit","end":""},{"old":"/__transmit/subscribe","type":0,"val":"subscribe","end":""}],
    types: placeholder as Registry['subscribe']['types'],
  },
  'unsubscribe': {
    methods: ["POST"],
    pattern: '/__transmit/unsubscribe',
    tokens: [{"old":"/__transmit/unsubscribe","type":0,"val":"__transmit","end":""},{"old":"/__transmit/unsubscribe","type":0,"val":"unsubscribe","end":""}],
    types: placeholder as Registry['unsubscribe']['types'],
  },
  'attachments': {
    methods: ["GET","HEAD"],
    pattern: '/attachments/:key/:name?',
    tokens: [{"old":"/attachments/:key/:name?","type":0,"val":"attachments","end":""},{"old":"/attachments/:key/:name?","type":1,"val":"key","end":""},{"old":"/attachments/:key/:name?","type":3,"val":"name","end":""}],
    types: placeholder as Registry['attachments']['types'],
  },
} as const satisfies Record<string, AdonisEndpoint>

export { routes }

export const registry = {
  routes,
  $tree: {} as ApiDefinition,
}

declare module '@tuyau/core/types' {
  export interface UserRegistry {
    routes: typeof routes
    $tree: ApiDefinition
  }
}
